services:
  laravel:
    build:
      context: ./backend
      target: prod  
    container_name: laravel_prod
    restart: always
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - startsync_prod_net


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: startsync
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_prod_data:/var/lib/mysql
    networks:
      - startsync_prod_net

networks:
  startsync_prod_net:

volumes:
  db_prod_data: